<?php
 use Magento\Framework\App\Action\Action;

 if(!$block->checkEnable()){ 
    return;
 }
  $products= $block->productToDisplay(); 
  $productsCount = count($products);
  
	if(!count($products)) { return; }
 
?>
 <h1 class="title"><?php echo __($this->getSectionTitle()); ?></h1>
<div class="owl-carousel owl-theme">
    <?php foreach ($products as $product) {  ?>
    <div class="item">
            
        <img alt="<?php echo $product->getName(); ?>"
            src="<?php echo $block->getImage($product->getSku()); ?>"
        />
        <?php 
        $showAddToCart = 1;
        $showWishlist = 1;
        $showCompare = 1;
        $productUrl   =  $product->getUrlModel()->getUrl($product); 
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $listProduct = $objectManager->create('\Magento\Catalog\Block\Product\ListProduct'); ?> 
        
        <div data-container="products-grid" class="product-item-info">
                            <a href="<?php echo $productUrl; ?>" class="product-sku" title='<?= $product->getModelNo(); ?>'>
                                <?= $product->getModelNo(); ?>
                            </a>

                            <div class="product-title">
                                <a href="<?php echo $productUrl; ?>" class="product-item-link" title='<?= $product->getName(); ?>'>
                                <?php echo $product->getName(); ?>
                                </a>
                            </div>
                            
							<?php 
								$finalPriceFlag = 0;
								$showPrice = 0;
								if ($product->getTypeId() == "configurable") {									
									$_children = $product->getTypeInstance()->getUsedProducts($product);
									foreach ($_children as $child){
										$childSalePrice = $child->getFinalPrice();
										if($childSalePrice){
											$finalPriceFlag = 1;
											$showPrice = 1;
										}
									}
								} else {
									$salePrice = $product->getFinalPrice();
									if ($salePrice) {
										$finalPriceFlag = 1;
										$showPrice = 1;
									}
								}
							?>
                            <?php if($showPrice) : ?>
                                <?php /* @escapeNotVerified */ echo $listProduct->getProductPrice($product); ?>
                            <?php endif; ?>
							
                            <div class="product-item product-item-actions">
                                <?php if($showAddToCart) { ?> 
                                    <div class="actions-primary">
                                        <?php if ($product->isSaleable()) {  ?>
                                            <?php $postParams = $block->getAddToCartPostParams($product);
                                            ?>
                                            
											<?php if ($finalPriceFlag) {  ?> 
                                            <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                                <input
                                                    type="hidden"
                                                    name="product"
                                                    value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>"
                                                >
                                                <input
                                                    type="hidden"
                                                    name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                    value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>"
                                                >
                                                <?= $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                        class="action tocart primary">
                                                    <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                </button>
                                            </form>
											
											<?php }  ?>
                                       
                                         
                                        <?php }  ?>
                                    </div> 
                                <?php }  ?>

                               
  
                                <div class="actions-secondary" data-role="add-to-links">
                                  
                                        <?php if ($this->helper(Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) :?>
                                                    <a href="#"
                                                       data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($product) ?>'
                                                       class="action towishlist" 
                                                       data-action="add-to-wishlist"
                                                       title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                    </a>
                                        <?php endif; ?>

                                            <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                <?php
                                                $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                ?>
                                                <a href="#" class="action-tocompare"
                                                   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($product);?>'
                                                   data-role="add-to-links"
                                                   title="<?php /* @escapeNotVerified */ echo __('Add to Compare'); ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                </a>
                                            <?php endif; ?>
                                       
                                </div>
                            </div>  <!-- new div -->
                         
                        </div>
    </div>
    <?php } ?>
</div>

<script type="text/x-magento-init">
{
"*": {
    "Nagarro_BestSeller/js/custom-slider": {
      
    }
}
}
</script>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "wishlist": {
                    "component": "Magento_Wishlist/js/view/wishlist"
                }
            }
        }
    }
}
</script>